#define strlen sf_strlen
#define strcpy sf_strcpy
#define strncpy sf_strncpy
#define gets sf_gets
#define scanf sf_scanf
#define sscanf sf_sscanf
#define getchar sf_getchar
#define strcat sf_strcat
#define sprintf sf_sprintf
#define atoi sf_atoi
#define vsnprintf sf_vsnprintf
#define vsprintf sf_vsprintf
#define vfprintf sf_vfprintf
#define puts sf_puts
#define putc sf_putc
#define putchar sf_putchar
#define getc sf_getc
#define memcpy sf_memcpy
#define fgets sf_fgets
#define memset sf_memset
#define vfscanf sf_vfscanf
#define fscanf sf_fscanf
#define snprintf sf_snprintf
#define strchr sf_strchr
#define strncat sf_strncat
#define memmove sf_memmove
#define strdup sf_strdup
#define strndup sf_strndup
#define is_valid_input_char sf_is_valid_input_char
